sudo: required
language: generic
services:
- docker

install:
 - sed -i "s/header_addl_info.*/header_addl_info = \"$(git describe --always)\"/g" ./custom/index.html.tmpl
 - docker build -t uneet/bugzilla-customisation .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push uneet/bugzilla-customisation;
    fi

# https://docs.travis-ci.com/user/deployment/script/
deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
      branch: master
