version: '2'
services:
    meteor:
      image: ulexus/meteor
      ports:
       - "8080:80"
      environment:
       - BUNDLE_URL=https://unee-t-media.s3-accelerate.amazonaws.com/frontend/staging.tar.gz
       - ROOT_URL=${ROOT_URL}
       - BUGZILLA_URL=${BUGZILLA_URL}
       - BUGZILLA_ADMIN_KEY=${BUGZILLA_ADMIN_KEY}
       - MONGO_URL=mongodb://root:${MONGO_PASSWORD}@${MONGO_CONNECT}
      logging:
            driver: awslogs
            options:
              awslogs-region: ap-southeast-1
              awslogs-group: meteor
